# Generated by Django 5.2.4 on 2026-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('sample_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('previous_crop', models.CharField(blank=True, max_length=200, null=True)),
                ('next_crop', models.CharField(blank=True, max_length=200, null=True)),
                ('date_sample_received', models.DateField(blank=True, null=True)),
                ('test_required', models.CharField(default='Soil Test', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
