# Generated by Django 5.2.4 on 2026-05-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilsample',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='updated_at',
        ),
    ]
